@startuml
top to bottom direction
package "Participant" {
  [Consumer]
}
package "Frontend Layer" {
  [Portals]
}
package "Web3 Wallet" {
  [Metamask]
}
package "RPC Module" {
  [RPC]
}
package "Authentication" {
  [SSI Wallet]
}
package "API Layer" {
  [APIs (Publish, Consumes)] - [Access Controller Provider]
  [Catalogue Cache]
}
package "Storage Layer" {
  [Storage Services] - [Compute Services]
[Access Controller Provider]-d->[Compute Services]
}
package "DLT Layer" {
  [Contracting Service] - [Federated Catalogue]
  [Contracting Service]-down->[Data Exchange Logging]
  [Data Exchange Logging] -down-> [Validator Nodes]
  [Federated Catalogue] -down-> [Smart Contract Templates]
  [Gaia-X Registry Node 2]
}
package "Gaia-X Compliance" {
  [Gaia-X Verifiers] -down-> [Policy Agent]
  [Gaia-X Verifiers]-right->[Gaia-X Issuer]
  [Gaia-X Registry Node 1] -right-> [Gaia-X Compliance Service]
}

Consumer --> Portals : consume
Portals -> Metamask
Metamask --> RPC
[Validator Nodes] -> RPC
Portals -> [SSI Wallet]
[SSI Wallet] -> [Access Controller Provider]
[SSI Wallet] -> Portals
Portals --> [Catalogue Cache]
[Federated Catalogue] --> [Catalogue Cache]
[Access Controller Provider] --> [Gaia-X Verifiers]
[SSI Wallet] --> [Gaia-X Verifiers]
[Gaia-X Registry Node 1] -> [Gaia-X Registry Node 2]
[Compute Services] <--> [Contracting Service]


@enduml