@startuml
top to bottom direction
package "Participant" {
  [Consumer] - [Publisher]
}
package "Frontend Layer" {
  [Portals]
}
package "Web3 Wallet" {
  [Metamask]
}
package "RPC Module" {
  [RPC]
}
package "Authentication" {
  [SSI Wallet]
}
package "API Layer" {
  [APIs (Publish, Consumes)] - [Access Controller Provider]
  [Catalogue Cache]
}
package "Storage Layer" {
  [Storage Services] - [Compute Services]

}
package "DLT Layer" {
  [Contracting Service] - [Federated Catalogue]
  [Contracting Service]-->[Data Exchange Logging]
  [Data Exchange Logging] --> [Validator Nodes]
  [Federated Catalogue] --> [Smart Contract Templates]
  [Contracting Service] --> [Smart Contract Templates]
  [Gaia-X Registry Node 2]
}
package "Gaia-X Compliance" {
  [Gaia-X Compliance Service] <-> [Gaia-X Registry Node 1]  
  [Gaia-X Verifiers] --> [Policy Agent]
  [Gaia-X Verifiers]->[Gaia-X Issuer]
}

Consumer --> Portals : consume
Publisher --> Portals: publish
Portals -> Metamask
Metamask --> RPC
[Validator Nodes] <- RPC
Portals -> [SSI Wallet]
[SSI Wallet] -> [Access Controller Provider]
[SSI Wallet] -> Portals
Portals --> [Catalogue Cache]
[Federated Catalogue] <-- [Catalogue Cache]
[Access Controller Provider]-->[Compute Services]
[Access Controller Provider] --> [Gaia-X Verifiers]
[SSI Wallet] --> [Gaia-X Verifiers]
[Gaia-X Registry Node 1] -> [Gaia-X Registry Node 2]
[Compute Services] <--> [Contracting Service]


@enduml