@startuml
top to bottom direction

Participant <-- ServiceProvider
Participant <-- Consumer
Participant <-- Federator

package "Participants" {
  [Trust Anchor]
  [Gaia-X AISBL]
}
package "Frontend Layer" {
  [Portals]
  [Exchange Logging Explorer]
  [Monitoring Frontends]
}
package "RPC Module" {
  [RPC]
}
package "Authentication" {
  [SSI Wallet]
  [Web3 Wallet]
  [VC Storage]
}
package "API Layer" {
  [APIs (Publish, Consume)] - [Access Controller Provider]
  [Catalogue Cache]
}
package "Storage Layer" {
  [Storage Services] <- [Compute Services]

}
package "DLT Layer" {
  [Contracting Service] - [Federated Catalogue]
  [Contracting Service]-->[Data Exchange Logging]
  [Data Exchange Logging] --> [Validator Nodes]
  [Contracting Service] --> [Smart Contract Templates]
  [Gaia-X Registry] --> [Compliance Service]
  [Federated Catalogue]
}
package "Gaia-X Compliance" {
  [Gaia-X Compliance Service] <-> [Gaia-X Registry Node 1]  
  [Gaia-X Verifiers] --> [Policy Agent]
  [Gaia-X Verifiers]->[Gaia-X Issuer]
}

Consumer --> Portals : consume
ServiceProvider --> Portals: publish
Portals -> Metamask
Metamask --> RPC
[Validator Nodes] <- RPC
Portals -> [SSI Wallet]
[SSI Wallet] -> [Access Controller Provider]
[SSI Wallet] -> Portals
Portals <-- [Catalogue Cache]
Portals --> [APIs (Publish, Consume)]
[APIs (Publish, Consume)] --> [Federated Catalogue]
[Federated Catalogue] --> [Catalogue Cache]
[Access Controller Provider]->[Compute Services]
[Access Controller Provider]-->[Federated Catalogue]
[Access Controller Provider] --> [Gaia-X Verifiers]
[SSI Wallet] --> [Gaia-X Verifiers]
[Gaia-X Registry Node 1] <-> [Gaia-X Registry Node 2]
[Compute Services] <--> [Contracting Service]

@enduml